### ISSUE TITLE
Failed to activate the language-stata package

### ISSUE THREAD

**Issue by leosergio06** [kylebarron/language-stata#116]
I haven't been able to install the language-stata in ATOM. When I try to install it I get the following message:

![image](https://user-images.githubusercontent.com/79174739/108138552-0907fb00-7073-11eb-9c34-a98adf6168b0.png)

1. ...
2. ...

**Atom**: 1.54.0 x64
**Electron**: 6.1.12
**OS**: macOS 11.2.1
**Thrown From**: [language-stata](https://github.com/kylebarron/language-stata) package 1.7.3

### Stack Trace

Failed to activate the language-stata package

```
At Arguments to CompositeDisposable.add must have a .dispose() method

TypeError: Arguments to CompositeDisposable.add must have a .dispose() method
    at assertDisposable (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1193727)
    at CompositeDisposable.add (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1194695)
    at Object.consumeProvider (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:162421)
    at Object.consumeProvider_4 (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:162229)
    at Provider.provide (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:1093694)
    at ServiceHub.provide (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3525828)
    at Package.activateServices (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3534167)
    at Package.activateNow (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3531143)
    at /Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3530467
    at Package.measure (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3528045)
    at /Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3530327
    at new Promise (<anonymous>)
    at Package.activate (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3530270)
    at PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:383646)
    at /Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:916751
    at r (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:911357)
    at s (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:1121312)
    at ChildProcess.<anonymous> (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:1121518)
    at ChildProcess.emit (events.js:200:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
```

### Commands

```
  6x -0:48.7.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
Hydrogen 2.14.7 
language-stata 1.7.3 
stata-exec 1.8.6 
Sublime-Style-Column-Selection 1.7.5 
```

**Comment by kylebarron** [comment]
Maybe Atom made a breaking change in the latest version, so the package might no longer work. It looks like this error exists for issues on other packages as well. It might be worth inspecting those issues. I don't use Stata anymore so I don't have the bandwidth to debug this.

**Comment by leosergio06** [comment]
Thanks for getting back to me.  I don't have the programming skill to debug
this.  It might be worth putting something on the language-stata website
warning potential users of the problem.  I spent several hours trying to
make it work.
